url: "https://jaredwhite.com" # the base hostname & protocol for your site, e.g. https://example.com

permalink: simple

content_engine: resource
template_engine: serbea

collections:
  now_entries:
    output: true
    sort_direction: descending
  newsletters:
    output: false # we'll just reference them from an archive page, but the actual issues are legacy static files
  podcast:
    output: true
    sort_direction: descending

# Other options you might want to investigate:
# 
# base_path: "/" # the subpath of your site, e.g. /blog
timezone: America/Los_Angeles
pagination:
  enabled: true
  per_page: 15
