services:
  - type: web
    name: jaredwhite2021
    env: static
    buildCommand: bin/bridgetown deploy
    staticPublishPath: ./output
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
    routes:
      - type: redirect
        source: /page/*
        destination: /posts/page/*